### ISSUE TITLE
Проект не собирается 

### ISSUE THREAD

**Issue by root1991** [Morya0903/SimpleScreen#1]
Error:(1, 0) Plugin with id 'com.android.application' not found.

**Comment by Morya0903** [comment]
What is your gradle buuld plugin version? There is the latest one set there

**Comment by root1991** [comment]
Дело не в версии. Вы не закомитили рутовый build.gradle

**Comment by Morya0903** [comment]
Вроде поправил, закинул всё что можно было.

**Comment by Morya0903** [comment]
Поправил, скачал, собрал, запустил. У меня всё работает.
